name: takuge-toolkit
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.4
  - pandas=1.4.3
  - pip=22.1.2
  - scikit-learn=1.1.1
  - regex=2022.7.9
  - gensim=4.2.0
  - pip:
    - mecab-python3==1.0.5
